name: Postman

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: matt-ball/newman-action@master
      with:
        collection: todos.postman_collection.json
        environment: todos.postman_environment.json
